
Page({
	data: {
		//用户全局信息
		userInfo: {},
		input: '',
		text1: `<p>来源&emsp;&emsp;  《求是》2021年第22期</p>`,
		text: `<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">坚持用马克思主义及其中国化创新理论武装全党</span></p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span class="font_family-KaiTi" data-source="cke"></span></p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">一</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;在前进道路上，我们一定要加强全党的理论武装，按照建设马克思主义学习型政党的要求，深入学习和掌握马克思列宁主义、毛泽东思想，深入学习和掌握中国特色社会主义理论体系，牢固树立辩证唯物主义和历史唯物主义世界观和方法论。</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke">（2012年11月15日在党的十八届一中全会上的讲话）</p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">二</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;首先要认真学习马克思主义理论，这是我们做好一切工作的看家本领，也是领导干部必须普遍掌握的工作制胜的看家本领。毛泽东同志曾经提出，&ldquo;如果我们党有一百个至二百个系统地而不是零碎地、实际地而不是空洞地学会了马克思列宁主义的同志，就会大大地提高我们党的战斗力量&rdquo;。这个任务，今天依然很现实地摆在我们党面前。只有学懂了马克思列宁主义、毛泽东思想、邓小平理论、&ldquo;三个代表&rdquo;重要思想、科学发展观，特别是领会了贯穿其中的马克思主义立场、观点、方法，才能心明眼亮，才能深刻认识和准确把握共产党执政规律、社会主义建设规律、人类社会发展规律，才能始终坚定理想信念，才能在纷繁复杂的形势下坚持科学指导思想和正确前进方向，才能带领人民走对路，才能把中国特色社会主义不断推向前进。</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke">（2013年3月1日在中央党校建校80周年庆祝大会暨2013年春季学期开学典礼上的讲话）</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke"><img style="width:100%;" src="https://red-ideological-and-political-classroom.oss-cn-beijing.aliyuncs.com/hot/1818-2018.jpg?versionId=CAEQJhiBgMC6ndPJlBgiIDZjNzYyMDU2MWZlMDQ4ZmY4NzIxOGEzY2Y4NjM4MGFm" /></p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">四</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;理论修养是干部综合素质的核心，理论上的成熟是政治上成熟的基础，政治上的坚定源于理论上的清醒。从一定意义上说，掌握马克思主义理论的深度，决定着政治敏感的程度、思维视野的广度、思想境界的高度。所以，我要求中央政治局集体学习加强对马克思主义基本原理的学习，已经安排学习了历史唯物主义、辩证唯物主义、马克思主义政治经济学方面的内容，以后还要安排。我们要保持浓厚的理论兴趣，自觉加强马克思主义基础理论学习，静下心来学习马克思、恩格斯、列宁、毛主席的原著，学习中国特色社会主义理论体系，学习党的十八大以来党的理论和路线方针政策创新成果，不断有所收获、有所提高。</p>
<p class="text_align-right xxqg-en-style" style="margin: 0px 0px 1.25rem; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important; overflow-wrap: break-word !important; word-break: normal !important;" data-source="cke">（2015年12月28日、29日在中共十八届中央政治局&ldquo;三严三实&rdquo;专题民主生活会上的讲话）</p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">五</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;时代是思想之母，实践是理论之源。实践发展永无止境，我们认识真理、进行理论创新就永无止境。今天，时代变化和我国发展的广度和深度远远超出了马克思主义经典作家当时的想象。同时，我国社会主义只有几十年实践、还处在初级阶段，事业越发展新情况新问题就越多，也就越需要我们在实践上大胆探索、在理论上不断突破。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;理论上不彻底，就难以服人。我们要以更加宽阔的眼界审视马克思主义在当代发展的现实基础和实践需要，坚持问题导向，坚持以我们正在做的事情为中心，聆听时代声音，更加深入地推动马克思主义同当代中国发展的具体实际相结合，不断开辟21世纪马克思主义发展新境界，让当代中国马克思主义放射出更加灿烂的真理光芒。</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke">（2016年7月1日在庆祝中国共产党成立95周年大会上的讲话）</p>
<p class="text_align-center" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">六</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;时代在变化，社会在发展，但马克思主义基本原理依然是科学真理。尽管我们所处的时代同马克思所处的时代相比发生了巨大而深刻的变化，但从世界社会主义500年的大视野来看，我们依然处在马克思主义所指明的历史时代。这是我们对马克思主义保持坚定信心、对社会主义保持必胜信念的科学根据。马克思主义就是我们党和人民事业不断发展的参天大树之根本，就是我们党和人民不断奋进的万里长河之泉源。背离或放弃马克思主义，我们党就会失去灵魂、迷失方向。在坚持以马克思主义为指导这一根本问题上，我们必须坚定不移，任何时候任何情况下都不能动摇。</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke">（2017年9月29日在十八届中央政治局第四十三次集体学习时的讲话）</p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: center !important;" data-source="cke"><img src="https://red-ideological-and-political-classroom.oss-cn-beijing.aliyuncs.com/hot/szkt.jpg?versionId=CAEQJhiBgMCckdLJlBgiIDdhZjg1ZmZkMzFlZTRmNTg5ODA5YjUyZTk5MzdiNDY0" /></p>
<p class="text_align-right" style="margin: 0px 0px 1.25rem; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; text-align: right !important;" data-source="cke"></p>`,
		input1: '',
		input2: '',
		input3: ''
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
