Page({
	data: {
		//用户全局信息
		userInfo: {},
		input: '',
    text1: `<p>来源&emsp;&emsp;  人民日报</p>`,
    data: 
    `<p style="text-align: left;text-indent:1000rpx;"><span style="font-size: 18px;"><strong>泰山巍峨伫立，黄河奔腾入海。</strong></span></p>
<p style="text-align: left;">&emsp;&emsp;</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;党的十八大以来，齐鲁大地发展日新月异。习近平总书记3次考察山东，多次发表重要讲话、作出重要指示批示，为山东发展把舵领航、指引方向。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;2021年10月，习近平总书记在山东考察时，嘱托山东&ldquo;努力在服务和融入新发展格局上走在前、在增强经济社会发展创新力上走在前、在推动黄河流域生态保护和高质量发展上走在前，不断改善人民生活、促进共同富裕，开创新时代社会主义现代化强省建设新局面&rdquo;。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;&ldquo;习近平总书记对山东的系列重要指示要求，一以贯之、一脉相承，赋予我们&lsquo;走在前、开新局&rsquo;的光荣使命。我们必须牢记嘱托走在前，勇担使命开新局，努力把总书记擘画的宏伟蓝图变为美好现实。&rdquo;山东省委主要负责同志说。</span></p>
<p style="text-align: left;"></p>
<p style="text-align: left;"><span style="font-size: 18px;"><strong>找准定位，在服务和融入新发展格局上走在前</strong></span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;作为东部沿海的农业大省、人口大省、经济大省，山东应当如何服务和融入新发展格局？</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp; 十年来，山东释放内需潜力，农业大省转向农业强省&mdash;&mdash;</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;粮食总产量连续8年稳定在千亿斤以上，农林牧渔业总产值2020年率先突破万亿元，农村居民人均可支配收入2021年首次突破2万元，家庭农场、农民合作社、农业龙头企业、农业社会化服务组织等新型农业经营主体数量均居全国前列&hellip;&hellip;一组组数据体现山东农业的硬核实力。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp; 2012年，淄博市博山区，房利军和他的山东华旅旅游发展有限公司一头扎进21平方公里的山沟沟，将秀美风景一步步建成红叶柿岩景区。据统计，2021年景区带动周边返乡村民约500人再就业，营业收入超过6000万元。&ldquo;一企带九村&rdquo;的示范效应正在凸显。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;东营市广饶县发展红色教育，聊城市东阿县壮大特色产业，高唐县推进数字乡村建设，济宁市培育&ldquo;乡村振兴合伙人&rdquo;&hellip;&hellip;放眼齐鲁大地，一个个乡村呈现农业强、农村美、农民富的崭新面貌。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;"> 十年来，山东畅通经济循环，开放大门越开越大&mdash;&mdash;</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;今年4月30日，一列中欧班列（齐鲁号）由济南南站发出，满载空调配件、太阳能设备等货物，驶向匈牙利布达佩斯。至此，&ldquo;齐鲁号&rdquo;用三年半的时间，开行总量超过5000列，稳居全国前列，国际运营线路达到52条，直达&ldquo;一带一路&rdquo;沿线23个国家54个城市。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;2021年，山东实现外贸进出口2.93万亿元，2012至2021年年均增长7.3%，高于全国年均增速。全省实际使用外资首次突破200亿美元，2012至2021年年均增长16.7%，规模跃居全国第四位。截至目前，已有223家世界500强企业在山东投资兴业。数据表明，十年间，山东省开放指标实现量的稳步增长和质的稳步提升。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;山东自贸试验区实施110项试点任务，形成142项制度创新成果；上海合作组织示范区全力推进国际物流、现代贸易、双向投资合作、商旅文交流发展&ldquo;四个中心&rdquo;建设，一批高能级平台支撑山东塑造开放型经济发展新优势。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;十年奋斗，山东发展基础更加坚实：三次产业齐头并进，供需两端协同发力，新老动能相得益彰，各类企业比翼齐飞，陆海资源统筹开发，交通运输四通八达，城乡区域均衡发展，对外开放升级，人文沃土深度耕作&hellip;&hellip;</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;&ldquo;牢记总书记的嘱托，山东将比较优势化为发展胜势，一定能够赢得主动权，既为一域增光，更为全局添彩，为全国大局作出山东贡献。&rdquo;山东省发改委副主任王栋说。</span></p>
<p style="text-align: left;"></p>
<p style="text-align: left;"><span style="font-size: 18px;"><strong>矢志创新，在增强经济社会发展创新力上走在前</strong></span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;黄海之滨，今年3月开工的万华化学低碳新材料产业园，建设场面热火朝天。万华化学集团股份有限公司董事长廖增太说，这里将为公司打造世界级高端石化产业基地增添强劲动力。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;烟台市锚定世界一流绿色石化产业基地目标，全力推动绿色石化产业链条化、园区化、智能化。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;从挖煤炭、烧水泥的&ldquo;一黑一灰&rdquo;，到高端装备、高端化工、新材料、新能源、新医药、新一代信息技术的&ldquo;两高四新&rdquo;，枣庄工业正重塑新辉煌。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;近些年，菏泽市瞄准生物医药产业，推动&ldquo;一港四园&rdquo;快速发展，投资额年均增长64%，产业规模年均增长30%、达到605亿元，实现3年翻一番。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp; 行走齐鲁大地，触摸经济发展脉搏，山东经济发展处处呈现新气象。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;这些年，山东坚决淘汰落后产能、改造提升传统动能、培育壮大新动能，顶住阵痛、迎难而上，新旧动能转换闯过一道道难关，经济发展步入快车道。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;工信部公布的6批共455家国家级&ldquo;单项冠军&rdquo;示范企业中，山东以109家居全国第一，其中淄博市以17家列全省第一。更令人惊喜的是，淄博老工业基地产业调整改造成效明显，这个走过120年历程的老工业城市，正在华丽转身。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;最近5年，山东省加速淘汰落后动能，压减钢铁产能占全国12%，万元GDP能耗下降18.4%。传统动能升级，实施500万元以上工业技改项目6.7万个，一批重大工程支撑强劲。新动能不断壮大，一批关键核心技术实现突破，高技术制造业增加值年均增长10%，&ldquo;四新&rdquo;经济增加值占比提高10个百分点，数字经济规模增长40%以上。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;从&ldquo;粗、黑、重&rdquo;到&ldquo;高、精、尖&rdquo;，山东省经济新旧动能转换呈现趋势性、转折性、关键性变化，迈向高质量发展呈现出由&ldquo;量&rdquo;到&ldquo;质&rdquo;、由&ldquo;形&rdquo;到&ldquo;势&rdquo;的根本性转变。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;深入学习贯彻习近平总书记重要指示精神，山东省把创新摆在发展全局的核心位置，深入实施包括加强科技研发创新、人才引育创新、营商环境创新等在内的&ldquo;十大创新&rdquo;行动计划，持续增强经济社会发展创新力。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;浪潮集团突破140多项关键技术，海尔集团在全球建立了&ldquo;10+N&rdquo;创新中心，中铁十四局不断刷新大盾构施工穿山越海新纪录&hellip;&hellip;一批优势企业，乘上创新东风，破浪前行；世界首套时速600公里的高速磁浮交通系统成功下线，全球首艘10万吨级智慧渔业大型工船投入运营&hellip;&hellip;在全国乃至全球创新版图上，山东元素愈发闪耀。</span></p>
<p style="text-align: left;"></p>
<p style="text-align: left;"><span style="font-size: 18px;"><strong> 勇当先锋，在推动黄河流域生态保护和高质量发展上走在前</strong></span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;菏泽市东明县长兴集乡兴东社区，白墙红瓦的小楼整齐排列，活动中心、幼儿园、学校、超市等一应俱全。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;&ldquo;家再也不在洪水里飘摇了！&rdquo;2021年3月，村民冯留海全家搬进一栋带院落的二层小洋房。历经3年奋战，山东60万黄河滩区群众喜圆安居梦，住上了安稳的家。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;万里黄河，奔腾依旧；千里滩区，换了新颜。从过去黄河滩里的&ldquo;穷窝窝&rdquo;，到如今幸福河畔的&ldquo;美家园&rdquo;，滩区百姓生活发生翻天覆地的变化。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;&ldquo;习近平总书记指明乡村全面振兴的方向，我们发展产业干劲更足！&rdquo;东营市垦利区杨庙社区党委书记张麦荣说，农业示范园、粮食烘干基地、果蔬冷链仓储物流园等项目相继落地，一个沿黄农业产业示范带正在形成。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;眼下，全国第一家陆海统筹型国家公园&mdash;&mdash;黄河口国家公园创建方案确定的8项任务圆满完成。 争当沿黄高质量发展&ldquo;排头兵&rdquo;，山东在沿黄9省区率先制定实施黄河流域生态环境保护专项规划，成立黄河流域首个生态环境观测站，与河南省率先建立黄河流域省际横向生态补偿机制。2021年，山东境内黄河干流国控断面水质全部达到地表水Ⅱ类标准。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;过去一年，山东出台黄河流域生态保护和高质量发展规划，390个年度重大项目完成投资2100亿元，286个项目集中开工，102个跨省合作事项加速落地，划定沿黄9市陆域生态红线，累计修复湿地2.3万亩。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;夏日的东平湖，碧波荡漾，芦苇丛生，青头潜鸭、白鹭等众多珍稀鸟类成群结队，动静之间尽显生物多样性之美。然而多年前的东平湖，25万多亩水域，网箱网围占到一半，采砂船日夜采砂，餐船餐余垃圾直排入湖&hellip;&hellip;</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;近年来，泰安市东平县坚定开展清网净湖、清违拆障等九大攻坚行动，清除违法建筑447处，清理网箱网围12.6万亩，湖水水质常年稳定达到地表水Ⅲ类水质。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;东平湖新生，折射出山东省落实黄河流域生态保护和高质量发展国家战略的决心和信心。发展环保产业培育新动能，改善生态环境质量提升群众幸福感，加强环保治理深入推进清洁生产&hellip;&hellip;7月12日，山东发布各地各部门&ldquo;抓环保促发展&rdquo;100个典型案例，各具特色，各有侧重。&ldquo;坚持生态优先、绿色发展的理念越来越深入人心，成为山东领导干部的自觉行动。&rdquo;山东省生态环境厅副厅长侯翠荣说。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-size: 18px;">&emsp;&emsp;大河流日夜，慷慨歌未央。山东干部群众凝心聚力，把&ldquo;绿水青山就是金山银山&rdquo;铭记于心，把&ldquo;山水林田湖草是生命共同体&rdquo;付之于行，把&ldquo;人与自然和谐发展&rdquo;落到实处。</span></p>
<p style="text-align: left;"></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"> &emsp;&emsp;&ldquo;走在前、开新局&rdquo;，其时已至、其势已成。亿万齐鲁儿女牢记嘱托，勇于担当、踔厉奋发，沿着习近平总书记指引的方向前进，努力在新时代社会主义现代化强省建设新征程上赢得更大荣光！（人民日报记者徐锦庚 侯琳良）</span></p>
<p style="text-align: left;"></p>`,
		input1: '',
		input2: '',
		input3: ''
	},
	onLoad(option) {
    this.init()
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
  async init() {},
  
});
