
Page({
	data: {
		//用户全局信息
		userInfo: {},
		input: '',
		text1: `<p>来源&emsp;&emsp; 上观新闻</p>`,
		text: `
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;习近平总书记指出：&ldquo;从全面建成小康社会到基本实现现代化，再到全面建成社会主义现代化强国，是新时代中国特色社会主义发展的战略安排。&rdquo;我们所推进的现代化，是人口规模巨大的现代化，是全体人民共同富裕的现代化，是物质文明和精神文明相协调的现代化，是人与自然和谐共生的现代化，是走和平发展道路的现代化。全面准确认识中国式现代化道路的新特征，需要对共同富裕有一个更为紧迫而深刻的认识。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">一、发展是硬道理，但&ldquo;发展起来以后的问题&rdquo;集中体现在财富如何分配和避免两极分化</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;改革开放以来，中国共产党人把握和平与发展时代主题，加快推进改革开放和现代化建设，迅速改变&ldquo;落后就要挨打&rdquo;的状况；紧紧抓住世界科技迅猛发展机遇，提出&ldquo;科学技术是第一生产力&rdquo;的重要论断，走上科技强国之路；顺应经济全球化趋势，实施一系列对外开放重大举措，创办经济特区，开发开放上海浦东，实施&ldquo;引进来&rdquo;&ldquo;走出去&rdquo;战略，加入世界贸易组织，推动中国经济融入世界，在世界经济格局中的占有率与影响力不断提升。进入新世纪，党抓住21世纪头20年的重要战略机遇期，集中精力，加快发展，取得的发展成就举世公认。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;邓小平同志在1992年南方谈话中明确说：&ldquo;发展才是硬道理。&rdquo;&ldquo;抓住时机，发展自己，关键是发展经济。&rdquo;&ldquo;在今后的现代化建设长过程中，出现若干个发展速度比较快、效益比较好的阶段，是必要的，也是能够办到的，我们就是要有这个雄心壮志！&rdquo;这些重要论断，定位了发展在中国式现代化进程中的不可替代性，成为全党和全国人民的共识。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;党的十八大以来，中国特色社会主义进入新时代，中国共产党统筹中华民族伟大复兴战略全局和世界百年未有之大变局，作出&ldquo;中国发展仍处于重要战略机遇期&rdquo;&ldquo;机遇和挑战之大都前所未有，总体上机遇大于挑战&rdquo;的战略判断，顺应和平、发展、合作、共赢的时代潮流，顺应世界多极化和国际关系民主化大势，顺应不可逆的经济全球化大势，对内推进高质量发展，把握新发展阶段、贯彻新发展理念、构建新发展格局；对外实行高水平开放，实施更大范围、更宽领域、更深层次的全面开放，促进合作共赢，在更好发展自己的同时更好融入并贡献世界。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;在庆祝中国共产党成立95周年大会上，习近平总书记指出，发展是党执政兴国的第一要务，是解决中国所有问题的关键。我国仍处于并将长期处于社会主义初级阶段的基本国情没有变，人民日益增长的物质文化需要同落后的社会生产之间的矛盾这一社会主要矛盾没有变，我国是世界上最大发展中国家的国际地位没有变。这是我们谋划发展的基本依据。党的十九大强调坚持新发展理念，明确指出发展是解决我国一切问题的基础和关键，发展必须是科学发展，必须坚定不移贯彻创新、协调、绿色、开放、共享的新发展理念。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;早在1993年，邓小平同志在与其弟的谈话中发人深省地说&ldquo;发展起来以后的问题不比不发展时少&rdquo;，更是警告&ldquo;富裕起来后财富怎样分配也是大问题&rdquo;，&ldquo;分配的问题大得很&rdquo;。&ldquo;这个问题要解决&rdquo;，虽然&ldquo;解决这个问题比解决发展起来的问题还困难&rdquo;，但是一定&ldquo;要利用各种手段、各种方法、各种方案解决这些问题&rdquo;，否则，&ldquo;少数人获得那么多财富，大多数人没有，这样发展下去总有一天会出问题。分配不公，会导致两极分化，到一定时候问题就会出来。&rdquo;</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;发展是硬道理，但&ldquo;发展起来以后的问题&rdquo;也在经济社会诸多层面日益凸显出来，必须引起高度重视：</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">&emsp;&emsp;一是发展面临&ldquo;三期叠加&rdquo;状况。</span>面对错综复杂的地缘政治格局与世界经济持续低迷的不确定性局面，面对我国经济增长速度换挡期、结构调整阵痛期、前期刺激政策消化期&ldquo;三期叠加&rdquo;的状况，经济形势可以说是变幻莫测、瞬息万变。改革开放以来，我们用几十年时间走完了发达国家几百年走过的发展历程，创造了世界发展的奇迹。随着经济总量不断增大，我们在发展中遇到了一系列新情况新问题。经济发展面临速度换挡节点，如同一个人，10岁至18岁期间个子猛长，18岁之后长个子的速度就慢下来了；经济发展面临结构调整节点，低端产业产能过剩要集中消化，中高端产业要加快发展，过去生产什么都赚钱、生产多少都能卖出去的情况不存在了；经济发展面临动力转换节点，低成本资源和要素投入形成的驱动力明显减弱，经济增长需要更多驱动力创新。此外，以牺牲环境、过度消耗资源、低成本劳动力为代价来换取经济的快速增长，这种传统模式难以为继，亟待转型升级实现高质量发展。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">&emsp;&emsp;二是发展面临社会主要矛盾的变化。</span>中国特色社会主义进入新时代，我国社会主要矛盾已经转化为人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。我国稳定解决了十几亿人的温饱问题，全面建成小康社会，人民美好生活需要日益广泛，不仅对物质文化生活提出了更高要求，而且在民主、法治、公平、正义、安全、环境等方面的要求日益增长。同时，我国社会生产力水平总体上显著提高，社会生产能力在很多方面进入世界前列，更加突出的问题是发展不平衡不充分，这已经成为满足人民日益增长的美好生活需要的主要制约因素。现在，我国发展不平衡不充分问题依然不容忽视，主要表现在：重点领域关键环节改革任务仍然艰巨，创新能力不适应高质量发展要求，农业基础还不稳固，城乡区域发展和收入分配差距较大，生态环保任重道远，民生保障存在短板，社会治理还有弱项。这些短板和不足，既有长期想解决但还没有解决好的问题，也有工作中重视不够而没有解决的问题；既有许多中长期的困难和问题，也有不少迫在眉睫的现实问题。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">&emsp;&emsp;三是发展面临的环境复杂多变。</span>发展起来以后，我国面临复杂多变的安全和发展环境，各种可以预见和难以预见的风险因素明显增多，各方面风险可能不断积累甚至集中显露。我们面临的风险是多方面的，有外部风险，也有内部风险；有一般风险，也有重大风险。重大风险既包括国内的经济、政治、意识形态、社会风险以及来自自然界的风险，也包括国际经济、政治、军事风险等。特别是要看到，各种威胁和挑战联动效应明显，各种矛盾风险挑战源、各类矛盾风险挑战点相互交织、相互作用。如果发生重大风险又扛不住，国家安全就可能面临重大威胁，推进中国式现代化道路、实现中华民族伟大复兴的进程就可能迟滞或被迫中断。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">&emsp;&emsp;四是发展成果&ldquo;分配的问题大得很&rdquo;。</span>应该肯定，社会各阶层、人民群众普遍从发展中获益很多，发展成果的分配问题也越来越受到重视，据今年5月12日中央财办分管日常工作的副主任韩文秀在发布会上介绍，过去十年，城乡居民人均可支配收入之比由2.88∶1降低到了2.5∶1，居民收入基尼系数由0.474降低到了0.466。但仅从基尼系数看，0.466也超过了国际上通用的警戒线标准0.4。值得注意的是，利益集团、权势团体、特权阶层通过围猎腐蚀等手段，占据和垄断资源，掠夺本应该由人民共享的发展成果，已经成为腐败的顽疾；互联网平台资本无序扩张造成平台经济野蛮生长和不良垄断行为，也会掠夺社会财富进而侵害公众利益；一些不法分子通过所谓金融创新、地下钱庄等深暗通道，挖空心思将发展成果及社会财富转移海外，企图掏空国库和人民的钱袋。毋庸讳言，两极分化的风险依然存在，其实质在于，人民群众本来是发展的主体和动力，但他们在发展中的成果却被剥夺，他们的获得感、幸福感和安全感大为降低，整个社会的发展也将难以为继。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&ldquo;发展起来以后的问题&rdquo;有很多，但最核心、最紧迫的问题，还是邓小平同志当年预见和警示的&ldquo;富裕起来后财富怎样分配也是大问题&rdquo;，就是如何避免两极分化、实现共同富裕，否则，&ldquo;发展下去总有一天会出问题。&rdquo;</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">二、共同富裕是体现社会主义本质特征的中国式现代化建设必由之路</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;发展是硬道理，这一全民共识伴随着改革开放进程深入人心。发展起来以后，共同富裕也应当成为举国上下的全民共识，贯穿中国式现代化建设新征程。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">（一）共同富裕是社会主义的本质要求</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;一部社会主义史，可以说就是一部追求公平正义的历史。空想社会主义思想家，都对资本主义进行了无情的揭露和批判，都认为资本主义社会不是一个公正合理的社会，都寻求建立一种没有阶级剥削和压迫的理想社会，在不同程度上主张对生产资料实行公有制。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;唯物史观和剩余价值学说的创立，使社会主义从空想变为科学。唯物史观从宏观上说明了社会主义的产生符合人类历史的发展规律，社会主义是脱胎于资本主义、基于物质利益的阶级斗争的产物。剩余价值的发现，揭示了无产阶级贫困的积累和资产阶级财富的积累及存在这种不平等现象的秘密，从微观上论证了资本主义的暂时性，并指出了资本主义到社会主义的实现道路和依靠力量。社会主义从空想到科学、从理论到实践，渐渐形成了三个基本特征：第一，所有权的公有制；第二，通过国家和政府的权力来进行财富分配；第三，它的目的是建造一个人类平等、没有匮乏、自由公正的理想社会。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;马克思关于共同富裕的理解是与生产目的紧密相关的。与资本主义生产目的是最大限度地追求剩余价值有着本质区别，社会主义&ldquo;生产将以所有的人富裕为目的&rdquo;。恩格斯指出，在社会主义制度下，&ldquo;通过社会化生产，不仅可能保证一切社会成员有富足的和一天比一天充裕的物质生活，而且还可能保证他们的体力和智力获得充分的自由的发展和运用&rdquo;。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;邓小平同志曾经说：&ldquo;社会主义的目的就是要全国人民共同富裕，不是两极分化。&rdquo;他还指出：&ldquo;社会主义最大的优越性就是共同富裕，这是体现社会主义本质的一个东西。如果搞两极分化，情况就不同了，民族矛盾、区域间矛盾、阶级矛盾都会发展，相应地中央和地方的矛盾也会发展，就可能出乱子&rdquo;。1992年视察南方时他指出：&ldquo;社会主义的本质，是解放生产力，发展生产力，消灭剥削，消除两极分化，最终达到共同富裕。&rdquo;</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">习近平总书记明确指出：&ldquo;我们党始终强调，中国特色社会主义，既坚持了科学社会主义基本原则，又根据时代条件赋予其鲜明的中国特色。这就是说，中国特色社会主义是社会主义，不是别的什么主义。&rdquo;&ldquo;共同富裕是社会主义的本质要求&rdquo;。这是把握发展阶段新变化，把逐步实现全体人民共同富裕摆在更加重要的位置上。从站起来到富起来再到强起来，中国已经进入扎实推动共同富裕的发展新时代和历史新阶段。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">（二）共同富裕是根植于中国历史文化传统基础上的价值追求</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;共同富裕，是自古以来炎黄子孙的一个基本理想。这一美好愿景集中表现为&ldquo;天道均平&rdquo;理念，在诸子百家思想中都有体现。譬如，晏子曾提出&ldquo;取财于富有者，以调剂贫乏者&rdquo;的治国主张；道家学派老子提出&ldquo;损有余而补不足&rdquo;；墨家学派墨子提出&ldquo;有力者疾以助人，有财者勉以分人，有道者劝以教人&rdquo;；法家学派管子则主张&ldquo;与天下人同利&rdquo;的治国方略。在儒家学派看来，&ldquo;不患寡而患不均，不患贫而患不安。&rdquo;这是稳定社会秩序的重要法则之一。这里的所谓&ldquo;均&rdquo;，并不意味着简单的平均主义，而是&ldquo;各得其分&rdquo;的公平状态。&ldquo;均平&rdquo;的价值指向不仅在于调整人与人之间的贫富差距，也拒斥&ldquo;国富而民穷&rdquo;的状态。《周易&middot;系辞下》明确提出：&ldquo;何以守位？曰仁。何以聚人？曰财。&rdquo;将予百姓以财富作为聚拢民心的重要手段。《论语》提出&ldquo;富与贵，是人之所欲也&rdquo;，荀子甚至提出&ldquo;下贫则上贫，下富则上富&rdquo;，将国富与民富辩证统一起来，社会财富不应过分聚集于国家而应分散于民。孟子说：&ldquo;老吾老以及人之老，幼吾幼以及人之幼。&rdquo;《礼记&middot;礼运》具体而生动地描绘了&ldquo;小康&rdquo;社会和&ldquo;大同&rdquo;社会的状态。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;秦朝末年，陈胜、吴广起义时喊的是&ldquo;苟富贵，无相忘&rdquo;；北宋末南宋初衰乱时，农民起义领袖钟相的口号是&ldquo;等贵贱、均贫富&rdquo;；清朝大厦将倾时，洪秀全的纲领为&ldquo;有田同耕，有饭同食，有钱同使，无处不均匀，无人不饱暖&rdquo;。即使在乱世中，中国人民对&ldquo;大同&rdquo;的平等理念仍心向往之，给后人留下宝贵的精神财富，但无不以失败告终。毛泽东同志在《论人民民主专政》一文中说：&ldquo;康有为写了《大同书》，但他没有也不可能找到一条到达大同的路。&rdquo;&ldquo;经过人民共和国到达社会主义和共产主义，到达阶级的消灭和世界的大同。&rdquo;这是一条真正的通往理想社会之路，也是通往国家富强、民族振兴、人民幸福之路。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;改革开放给中国社会带来了翻天覆地的变化，使人民生活实现了从温饱不足到总体小康的历史性跨越，我们党带领全国各族人民成功地走出了一条中国特色社会主义道路。习近平总书记在庆祝中国共产党成立100周年大会上庄严宣告：&ldquo;经过全党全国各族人民持续奋斗，我们实现了第一个百年奋斗目标，在中华大地上全面建成了小康社会，历史性地解决了绝对贫困问题。&rdquo;今天，我们比历史上任何时期都更加接近大同理想，更加接近中华民族伟大复兴的中国梦。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">（三）共同富裕是中国式现代化的重要特征</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;纵观世界现代化近300年的历史，西方先行国家的现代化无不建立在&ldquo;血与火&rdquo;的基础之上，刻上了&ldquo;丛林法则&rdquo;与&ldquo;霸凌主义&rdquo;的显著标签，无论是资本原始积累，还是原材料产地和商品市场拓展，对内的剥削和压迫、对外的侵略和殖民，是这些国家现代化的实现手段。时至今日，尽管受到国际条约的约束，国家现代化与暴力的结合已经变得十分隐蔽，但是西方发达国家依然依靠其传统优势地位和霸权掌控着国际秩序，并通过经济操控、政治干预甚至代理人战争等手段，对世界其他国家和地区进行控制和利用，从而达到维系其领先地位的目的。恃强凌弱、弱肉强食、尔虞我诈的&ldquo;丛林法则&rdquo;&ldquo;霸凌主义&rdquo;，成为其他国家实现现代化的巨大障碍。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;西方现代化模式，也必然导致了人类文明进步的全球性问题，其中的顽疾就是贫富分化。特别是国际金融危机引发严重的全球衰退以来，两极分化和贫富矛盾加剧，成为欧美西方世界最突出的社会问题。贫富分化加剧的最明显标志是所谓&ldquo;中产阶级挤压&rdquo;，越来越多中产阶级成员收入下降，以至沦为下层阶级。据英国牛津经济研究院测算，2020年3月至2021年1月，美国国内收入排名前20%人口的财富增加约2万亿美元，而排名后20%人口的财富减少逾1800亿美元。美国知名投资人斯坦利&middot;德鲁肯米勒直言，美联储不计后果地印钞，是加剧社会财富水平两极分化的罪魁祸首。贫富分化加剧社会不公，即使是美国这样的现代化国家，贫富分化痼疾难除，美式民主早已经沦为&ldquo;富人有、富人治、富人享&rdquo;的游戏，所谓&ldquo;人人生而平等&rdquo;只能成为空话。有识之士如韩国前总统文在寅就曾指出，贫富两极分化和经济不平等是国际社会共同面临的问题，不解决这些问题，就无法实现可持续发展。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;习近平总书记指出，当前，全球收入不平等问金题突出，一些国家贫富分化，中产阶层塌陷，导致社会撕裂、政治极化、民粹主义泛滥，教训十分深刻！我国必须坚决防止两极分化，促进共同富裕，实现社会和谐安定。邓小平同志也曾经谈到，&ldquo;如果我们的政策导致两极分化，我们就失败了；如果产生了什么新的资产阶级，那我们就真是走了邪路了&rdquo;。这就昭示我们，中国式现代化道路，绝不能走传统的西方现代化之路，即不能走产生资产阶级的邪路，也不能走导致两极分化的失败之路，那就只能对外坚持以和平发展作为实现现代化的根本遵循，对内坚持实现全体人民共同富裕的现代化，只能走全体人民共同富裕之路。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;共同富裕是社会主义的本质要求，是扎根于中国历史文化传统基础上的价值追求，是中国式现代化的重要特征。</p>
<p class="text_align-justify text_indent-2em xxqg-en-style" style="margin: 0px 0px 1.25rem; text-align: justify; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc; overflow-wrap: break-word !important; word-break: normal !important;" data-source="cke"><span style="font-weight: bolder;" data-source="cke">三、扎实推动共同富裕，在高质量发展中实现&ldquo;共建共富&rdquo;&ldquo;逐步共富&rdquo;&ldquo;全民共富&rdquo;&ldquo;全面富裕&rdquo;</span></p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;中国共产党人既是充满激情的理想主义者，也是脚踏实地的实事求是者。这也体现在对发展和共同富裕的理论认知和战略安排上。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;邓小平同志在南方谈话中曾设想：走社会主义道路，就是要逐步实现共同富裕。共同富裕的构想是这样提出的：一部分地区有条件先发展起来，一部分地区发展慢点，先发展起来的地区带动后发展的地区，最终达到共同富裕。如果富的愈来愈富，穷的愈来愈穷，两极分化就会产生，而社会主义制度就应该而且能够避免两极分化。解决的办法之一，就是先富起来的地区多交点利税，支持贫困地区的发展。当然，太早这样办也不行，现在不能削弱发达地区的活力，也不能鼓励吃&ldquo;大锅饭&rdquo;。什么时候突出地提出和解决这个问题，在什么基础上提出和解决这个问题，要研究。可以设想，在本世纪末达到小康水平的时候，就要突出地提出和解决这个问题。到那个时候，发达地区要继续发展，并通过多交利税和技术转让等方式大力支持不发达地区。不发达地区又大都是拥有丰富资源的地区，发展潜力是很大的。总之，就全国范围来说，我们一定能够逐步顺利解决沿海同内地贫富差距的问题。现在回过头来看，我们不能不佩服邓小平同志的准确预见和战略安排。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;党的十八大以来，习近平总书记多次指出：共同富裕是社会主义的本质要求，是人民群众的共同期盼。我们推动经济社会发展，归根结底是要实现全体人民共同富裕。他强调：&ldquo;治国之道，富民为始。&rdquo;我们始终坚定人民立场，强调消除贫困、改善民生、实现共同富裕是社会主义的本质要求，是我们党坚持全心全意为人民服务根本宗旨的重要体现，是党和政府的重大责任。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;&ldquo;究天人之际，通古今之变&rdquo;，中国共产党人探索开辟了中国特色社会主义道路。中国特色社会主义，从传统社会主义中汲取了深刻的经验教训，并借鉴了资本主义制度中有利于发展社会生产力、有利于创造社会物质财富的合理成分，比如市场经济、资本效率、资源配置、产业变革等，同时坚守了社会主义以人民为中心、以公有制为主体、维护大多数人利益、促进社会公平正义等本质特征。如今，在中国式现代化建设新征程上，扎实推动共同富裕，是坚定中国特色社会主义&ldquo;四个自信&rdquo;的实现路径，在推进过程中必须注意把握好以下几个方面的理论与实践问题：</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;一是要充分认识到，实现共同富裕不仅是经济问题，而且是关系党的执政基础的重大政治问题，在全面建设社会主义现代化国家新征程中，我们必须把促进全体人民共同富裕摆在更加重要的位置，脚踏实地、久久为功，向着这个目标更加积极有为地进行努力。中国共产党干革命、搞建设、谋发展，都是为了让人民过上幸福生活。我们不能片面地认为，只有发展成果丰富到足够分配时，只有条件全部具备时，才能推动共同富裕；不能错误地认为，提倡和推动共同富裕，会挫伤先富裕起来的人的积极性，会影响发展；不能模糊地认为，两极分化是发展过程中的必然现象、合理存在；更不能极端地认为，共同富裕就是新的&ldquo;打土豪、分田地&rdquo;，是搞新的&ldquo;均贫富&rdquo;，会导致&ldquo;共同贫困&rdquo;。冰冻三尺，非一日之寒，如果不能适时适机积极解决两极分化问题，最终发展成果和现代化愿景都将沦为泡影，甚至会产生灾难性后果。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;二是要廓清和丰富共同富裕的内涵，共同富裕是全体人民共同富裕，是人民群众物质生活和精神生活都富裕，不是少数人的富裕，也不是整齐划一的平均主义。以承担起&ldquo;高质量发展建设共同富裕示范区&rdquo;国家使命的浙江为例，围绕推动收入分配制度改革试验区建设，出台&ldquo;扩中&rdquo;（扩大中等收入人群）&ldquo;提低&rdquo;（提高低收入人群）行动方案，核心指标是到2025年，浙江家庭年可支配收入10万-50万元群体比例达到80%，20-60万元群体比例达到45%，目标是推动率先基本形成以中等收入群体为主体的橄榄型社会结构。具体实施路径上，&ldquo;扩中&rdquo;包括促就业、激活力、拓渠道、优分配、强能力、重帮扶、减负担、扬新风这八大路径。在推动八大路径全面落地基础上，瞄准增收潜力大、带动能力强的&ldquo;扩中&rdquo;重点群体和收入水平低、发展能力弱的&ldquo;提低&rdquo;重点群体，浙江省提出了当前阶段需要重点关注的九类群体，包括技术工人、科研人员、中小企业主和个体工商户、高校毕业生、高素质农民、新就业形态从业人员、进城农民工、低收入农户、困难群体等，率先推出一批差别化收入分配激励政策。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;三是要分目标、分阶段促进共同富裕，力争到2035年，全体人民共同富裕取得更为明显的实质性进展，基本公共服务实现均等化；到本世纪中叶，全体人民共同富裕基本实现，居民收入和实际消费水平差距缩小到合理区间。整个现代化过程中要统筹需要和可能，把保障和改善民生建立在经济发展和财力可持续的基础之上，不要好高骛远，吊高胃口，作兑现不了的承诺，坚决防止落入&ldquo;福利主义&rdquo;养懒汉的陷阱；要允许一部分人先富起来，同时要强调先富带后富、帮后富，重点鼓励辛勤劳动、合法经营、敢于创业的致富带头人，靠偏门致富不能提倡，违法违规的要依法处理；要防止社会阶层固化，畅通向上流动通道，给更多人创造致富机会，形成人人参与的发展环境，避免&ldquo;内卷&rdquo;&ldquo;躺平&rdquo;，要靠勤劳智慧来创造共同富裕。</p>
<p class="text_align-justify text_indent-2em" style="margin: 0px 0px 1.25rem; text-align: justify; overflow-wrap: break-word; line-height: calc(var(--font-size-larger)*1.9125rem); min-height: calc(var(--font-size-larger)*1.9125rem); color: #333333; font-family: FZYaSongS-R-GB, FZYaSong-M-GBK, 'PingFang SC', miui, system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; background-color: #fafbfc;" data-source="cke">&emsp;&emsp;四是要坚持以人民为中心的发展思想，坚持在发展中保障和改善民生，把握新发展阶段，贯彻新发展理念，构建新发展格局，实现高质量发展，以高质量发展来解决&ldquo;发展起来以后的问题&rdquo;，在高质量发展中促进共同富裕。这就要正确处理效率和公平的关系，在继续&ldquo;做大蛋糕&rdquo;基础上更重视&ldquo;分好蛋糕&rdquo;，建立健全&ldquo;先富带后富&rdquo;机制，构建初次分配、再分配、三次分配协调配套的基础性制度安排；加大税收、社保、转移支付等调节力度并提高精准性，扩大中等收入群体比重，增加低收入群体收入，合理调节高收入，取缔非法收入，形成中间大、两头小的橄榄型分配结构；注重提高收入分配质量，自觉主动解决、不断缩小地区差距、城乡差距、收入差距等问题，使发展成果更多更公平惠及全体人民，不断增强人民群众获得感、幸福感、安全感。（作者分别为上海社会科学院研究员、原副院长，上海话剧艺术中心党委副书记、纪委书记）</p>`,
		input1: '',
		input2: '',
		input3: ''
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
